language: php
php:
  - '5.6'
  - '7.0'
  - 'nightly'
  - 'hhvm'
env:
  matrix:
    - COMPOSER_ARGS="install"
    - COMPOSER_ARGS="update"
    - COMPOSER_ARGS="update --prefer-stable"
    - COMPOSER_ARGS="update --prefer-lowest"
    - COMPOSER_ARGS="update --no-dev"
install:
  - 'composer $COMPOSER_ARGS'
  - 'sudo mysql -e "CREATE DATABASE phuria_test"'
  - 'sudo mysql phuria_test < tests/Phuria/SQLBuilder/Test/Resources/schema.sql'
script:
  - 'phpunit tests'